---
title:  "6060 Practice Quiz 7"
author: "Veesta Mavandadi"
output:
  pdf_document:
    number_sections: yes
    toc_depth: 3
    
---
#Hypotheses

The present study will examine the relationship between self-esteem and a)academic performance, b)quality of dating relationships, and c) quality of friendships. We will be quanitying the effect size as small, medium or large according to the correlational effect sizes presented in Bosco, Aguinis, Singh, Field and Pierce (2015). Firstly, we predict a large, positive correlation between self-esteem and academic performance. Secondly, we predict that the relationship between self-esteem and quality of dating relationships will be negatively related and will also reveal a large effect size. Finally, we predict that self-esteem will demonstrate a weak, positive correlation with quality of friendships. 

#Analysis Plan

We intend to evaluate what sample sizes will be required to achieve a strong power value of .80 with a significance of p<=.05. Additionally, we will be utilizing a SafeGaurd Power Analysis approach that utilizes the lower bound of the confidence interval for a Pearson correlation to make a safe estimate of the sample size required. 

For hypothesis 1, when conducting a traditional power analysis, it is revealed that a sample size of n=28 to achieve the desired power of .8. 

For hypothesis 2, we must utilize the available Pearson correlation value and sample size from the published study and examine the examine the lower bound of the confidence interval and use that value in the Safegaurd power analysis. The Safegaurd Power Analysis reveals that *n*=32 is required to achieve the desired power. 

For hypothesis 3, we will utilize an estimated *r*=.07 which depicts a weak or small effect size. This small effect size value has been recommended by Bosco, Aguinis, Singh, Field and Pierce (2015). The present analysis reveals that *n*=1598 would be sufficient to produce a power of .80. 

For the overall study, we would need to use the largest sample size found via the power analysis, so *N*=1600 would be efficient. 

#Analysis B 

For hypothesis 1, when conducting a power analysis by examining confidence interval widths, a sample size of n= 40 would provide me with CI 95%[.22,.70] whose width is smaller than the effect size of *r*=.5.

For hypothesis 2, when conducting a power analysis where we have prior literature, a sample size of *n*= 50 would provide me with a CI 95%[-.66,-.22]. 

For hypothesis 3, when assuming a weak positive correlation of *r*=.07, a sample size of *n*=3200 would provide me with a CI 95%[.0354, .105]. 

For the overall study, we need to use the largest sample size utilizing a safegaurd analysis approach, so *N*=3200 would be efficient.